// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Context;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DealershipContext))]
    partial class DealershipContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication1.Models.UserModel", b =>
                {
                    b.Property<int>("idUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUser"), 1L, 1);

                    b.Property<string>("nombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idUser");

                    b.ToTable("userModels");
                });

            modelBuilder.Entity("WebApplication1.Models.VehicleModel", b =>
                {
                    b.Property<int>("idVehicle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVehicle"), 1L, 1);

                    b.Property<int>("añoAutomovil")
                        .HasColumnType("int");

                    b.Property<int>("kilometrosAutomovil")
                        .HasColumnType("int");

                    b.Property<string>("marcaAutomovil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modeloAutomovil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("precioAutomovil")
                        .HasColumnType("int");

                    b.HasKey("idVehicle");

                    b.ToTable("vehicleModels");
                });
#pragma warning restore 612, 618
        }
    }
}
